//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int EmployeeId { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Age { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string City { get; set; }
        public string Date { get; set; }
        public string Image { get; set; }
        public string Role { get; set; }
        public string UName { get; set; }
        public string Password { get; set; }
    
        public virtual BankInfo BankInfo { get; set; }
        public virtual BranchInfo BranchInfo { get; set; }
        public virtual DesignationInfo DesignationInfo { get; set; }
        public virtual GenderInfo GenderInfo { get; set; }
    }
}
