//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Brank_InfomationEntities : DbContext
    {
        public Brank_InfomationEntities()
            : base("name=Brank_InfomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BranchInfo> BranchInfoes { get; set; }
        public virtual DbSet<DesignationInfo> DesignationInfoes { get; set; }
        public virtual DbSet<GenderInfo> GenderInfoes { get; set; }
        public virtual DbSet<BankInfo> BankInfoes { get; set; }
        public virtual DbSet<EmployeeInfo> EmployeeInfoes { get; set; }
        public virtual DbSet<Rpt_EmployeeInfo> Rpt_EmployeeInfo { get; set; }
    }
}
