//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_EmployeeInfo
    {
        public int EmployeeId { get; set; }
        public string EmpName { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string DesignationName { get; set; }
        public string GenderName { get; set; }
        public string Age { get; set; }
        public string Salary { get; set; }
        public string Date { get; set; }
        public string Image { get; set; }
    }
}
